version: 2
project_name: tufw
env:
  - GO111MODULE=on
before:
    hooks:
      # You may remove this if you don't use go modules.
      - go mod download
      - go mod tidy
builds:
  - main: ./cmd/tufw/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm64
      - amd64
      - '386'
archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
snapshot:
  version_template: "{{ .Version }}-SNAPSHOT-{{ .CommitTimestamp }}-{{ .ShortCommit }}"
changelog:
    sort: asc
    filters:
        exclude:
          - '^docs:'
          - '^test:'
nfpms:
  - id: packages
    homepage: https://github.com/peltho/tufw
    maintainer: Thomas Pellegatta <pellegatta.thomas@gmail.com>
    description: "A terminal user interface for ufw"
    license: MIT
    formats:
      - deb
      - rpm
    dependencies:
      - ufw
aurs:
  - name: tufw
    description: "Terminal UI for ufw"
    homepage: "https://github.com/peltho/tufw"
    maintainers:
      - "Thomas Pellegatta <pellegatta.thomas@gmail.com>"
    license: "MIT"
    git_url: "ssh://aur@aur.archlinux.org/tufw.git"
    skip_upload: false
    private_key: /Users/thomas/.ssh/rsa_aur
    depends:
      - ufw
    commit_author:
        name: goreleaserbot
        email: bot@goreleaser.com
env_files:
    github_token: .github-token
